### ISSUE TITLE
Could you build a vivo android-29/arm64-v8a version minicap.so file

### ISSUE THREAD

**Issue by taylortaurus** [varundtsfi/Xiaomi_Vector_issue#2]

**Comment by varundtsfi** [comment]
Sure I will just wait for this weekend please

**Comment by varundtsfi** [comment]
get the verified vivo android 10 binary from following link

https://github.com/varundtsfi/Xiaomi_Vector_issue/tree/main/Vivo/android-29/arm64-v8a

**Comment by taylortaurus** [comment]
> get the verified vivo android 10 binary from following link
> 
> https://github.com/varundtsfi/Xiaomi_Vector_issue/tree/main/Vivo/android-29/arm64-v8a

thx. i will try it next week.

**Comment by wangzi1325** [comment]
It works! thx.

**Comment by varundtsfi** [comment]
Now I am closing this issue.
