### ISSUE TITLE
minicap.so is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by xdien** [varundtsfi/Xiaomi_Vector_issue#7]
Xiaomi Mi9.
Build from source [minicap](https://github.com/DeviceFarmer/minicap)
```
CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": "/data/local/tmp/minicap.so" is 32-bit instead of 64-bit
```

Can you rebuild with 64bit?
Thank you so much!

**Comment by xdien** [comment]
Problem solved using nw_minicap.so!

**Comment by varundtsfi** [comment]
Hi @xdien  do you have nw_minkcap.so for android 12. 
Can you please share.
